import { MigrationInterface, QueryRunner } from "typeorm";

export class FakePosts1614996360951 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
 insert into post (title, text, "creatorId") values ('Badger, european', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 1);
insert into post (title, text, "creatorId") values ('Deer, swamp', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 1);
insert into post (title, text, "creatorId") values ('American beaver', 'orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', 1);
insert into post (title, text, "creatorId") values ('Penguin, galapagos', 'commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi', 1);
insert into post (title, text, "creatorId") values ('Gull, silver', 'blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est', 1);
insert into post (title, text, "creatorId") values ('Bandicoot, southern brown', 'gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 1);
insert into post (title, text, "creatorId") values ('Yellow baboon', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien', 1);
insert into post (title, text, "creatorId") values ('Heron, grey', 'libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo', 1);
insert into post (title, text, "creatorId") values ('Stanley crane', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 1);
insert into post (title, text, "creatorId") values ('Godwit, hudsonian', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 1);
insert into post (title, text, "creatorId") values ('Little brown bat', 'donec quis orci eget orci vehicula condimentum curabitur in libero', 1);
insert into post (title, text, "creatorId") values ('Sun gazer', 'at dolor quis odio consequat varius integer ac leo pellentesque', 1);
insert into post (title, text, "creatorId") values ('Barking gecko', 'vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et', 1);
insert into post (title, text, "creatorId") values ('Land iguana', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in', 1);
insert into post (title, text, "creatorId") values ('Common grenadier', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 1);
insert into post (title, text, "creatorId") values ('Macaw, red and blue', 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 1);
insert into post (title, text, "creatorId") values ('Gull, herring', 'massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida', 1);
insert into post (title, text, "creatorId") values ('Peccary, white-lipped', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', 1);
insert into post (title, text, "creatorId") values ('Crowned eagle', 'libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla', 1);
insert into post (title, text, "creatorId") values ('Fork-tailed drongo', 'sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel', 1);
insert into post (title, text, "creatorId") values ('Squirrel, golden-mantled ground', 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas', 1);
insert into post (title, text, "creatorId") values ('Pie, rufous tree', 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer', 1);
insert into post (title, text, "creatorId") values ('Lizard, blue-tongued', 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 1);
insert into post (title, text, "creatorId") values ('Black-eyed bulbul', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 1);
insert into post (title, text, "creatorId") values ('Egyptian viper', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel', 1);
insert into post (title, text, "creatorId") values ('Kangaroo, brush-tailed rat', 'justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 1);
insert into post (title, text, "creatorId") values ('Snake (unidentified)', 'justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse', 1);
insert into post (title, text, "creatorId") values ('Tortoise, asian foreset', 'ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a', 1);
insert into post (title, text, "creatorId") values ('Dove, ring', 'sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 1);
insert into post (title, text, "creatorId") values ('Viper, egyptian', 'curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 1);
insert into post (title, text, "creatorId") values ('Snake, western patch-nosed', 'justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 1);
insert into post (title, text, "creatorId") values ('Blue catfish', 'curabitur in libero ut massa volutpat convallis morbi odio odio', 1);
insert into post (title, text, "creatorId") values ('South American sea lion', 'justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi', 1);
insert into post (title, text, "creatorId") values ('Woodchuck', 'in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem', 1);
insert into post (title, text, "creatorId") values ('Kookaburra, laughing', 'faucibus cursus urna ut tellus nulla ut erat id mauris', 1);
insert into post (title, text, "creatorId") values ('Jaguar', 'vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque', 1);
insert into post (title, text, "creatorId") values ('Kalahari scrub robin', 'nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam', 1);
insert into post (title, text, "creatorId") values ('Yellow-rumped siskin', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 1);
insert into post (title, text, "creatorId") values ('Owl, great horned', 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna', 1);
insert into post (title, text, "creatorId") values ('Salmon pink bird eater tarantula', 'nonummy integer non velit donec diam neque vestibulum eget vulputate', 1);
insert into post (title, text, "creatorId") values ('Squirrel, eurasian red', 'magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum', 1);
insert into post (title, text, "creatorId") values ('Duiker, gray', 'elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula', 1);
insert into post (title, text, "creatorId") values ('Goose, greylag', 'ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi', 1);
insert into post (title, text, "creatorId") values ('Sociable weaver', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam', 1);
insert into post (title, text, "creatorId") values ('Tern, white-winged', 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 1);
insert into post (title, text, "creatorId") values ('Black curlew', 'aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui', 1);
insert into post (title, text, "creatorId") values ('Asian water dragon', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut', 1);
insert into post (title, text, "creatorId") values ('Python, carpet', 'amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', 1);
insert into post (title, text, "creatorId") values ('Leopard, indian', 'lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum', 1);
insert into post (title, text, "creatorId") values ('California sea lion', 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut', 1);
insert into post (title, text, "creatorId") values ('American alligator', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis', 1);
insert into post (title, text, "creatorId") values ('Fisher', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis', 1);
insert into post (title, text, "creatorId") values ('Asian water dragon', 'nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate', 1);
insert into post (title, text, "creatorId") values ('Eagle, tawny', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 1);
insert into post (title, text, "creatorId") values ('Legaan, ground', 'a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 1);
insert into post (title, text, "creatorId") values ('Dolphin, striped', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta', 1);
insert into post (title, text, "creatorId") values ('Bat, asian false vampire', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 1);
insert into post (title, text, "creatorId") values ('Eastern box turtle', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget', 1);
insert into post (title, text, "creatorId") values ('King cormorant', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit', 1);
insert into post (title, text, "creatorId") values ('Rhinoceros, white', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum', 1);
insert into post (title, text, "creatorId") values ('Kori bustard', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam', 1);
insert into post (title, text, "creatorId") values ('Mourning collared dove', 'dui luctus rutrum nulla tellus in sagittis dui vel nisl', 1);
insert into post (title, text, "creatorId") values ('Sage grouse', 'venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada', 1);
insert into post (title, text, "creatorId") values ('Bustard, denham''s', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 1);
insert into post (title, text, "creatorId") values ('Lesser flamingo', 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin', 1);
insert into post (title, text, "creatorId") values ('Cape clawless otter', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 1);
insert into post (title, text, "creatorId") values ('Pallas''s fish eagle', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 1);
insert into post (title, text, "creatorId") values ('Smith''s bush squirrel', 'sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque', 1);
insert into post (title, text, "creatorId") values ('White-throated toucan', 'lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat', 1);
insert into post (title, text, "creatorId") values ('Jackal, asiatic', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 1);
insert into post (title, text, "creatorId") values ('Capuchin, white-fronted', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu', 1);
insert into post (title, text, "creatorId") values ('Laughing kookaburra', 'in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus', 1);
insert into post (title, text, "creatorId") values ('Mississippi alligator', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae', 1);
insert into post (title, text, "creatorId") values ('Blue and gold macaw', 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 1);
insert into post (title, text, "creatorId") values ('Bunting, crested', 'imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit', 1);
insert into post (title, text, "creatorId") values ('Jackal, black-backed', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia', 1);
insert into post (title, text, "creatorId") values ('Eastern box turtle', 'pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac', 1);
insert into post (title, text, "creatorId") values ('Lapwing (unidentified)', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', 1);
insert into post (title, text, "creatorId") values ('Bird, pied butcher', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae', 1);
insert into post (title, text, "creatorId") values ('Red-tailed cockatoo', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 1);
insert into post (title, text, "creatorId") values ('Cobra (unidentified)', 'proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 1);
insert into post (title, text, "creatorId") values ('Red-winged hawk (unidentified)', 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis', 1);
insert into post (title, text, "creatorId") values ('Giraffe', 'maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque', 1);
insert into post (title, text, "creatorId") values ('Bleu, blue-breasted cordon', 'sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 1);
insert into post (title, text, "creatorId") values ('Galapagos albatross', 'praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in', 1);
insert into post (title, text, "creatorId") values ('Monkey, rhesus', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies', 1);
insert into post (title, text, "creatorId") values ('White-throated kingfisher', 'faucibus cursus urna ut tellus nulla ut erat id mauris', 1);
insert into post (title, text, "creatorId") values ('Gray heron', 'eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a', 1);
insert into post (title, text, "creatorId") values ('Tortoise, burmese brown mountain', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 1);
insert into post (title, text, "creatorId") values ('Black-tailed prairie dog', 'quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis', 1);
insert into post (title, text, "creatorId") values ('Eagle, crowned', 'id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 1);
insert into post (title, text, "creatorId") values ('Coqui partridge', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget', 1);
insert into post (title, text, "creatorId") values ('Bear, american black', 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci', 1);
insert into post (title, text, "creatorId") values ('Squirrel, eastern fox', 'massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo', 1);
insert into post (title, text, "creatorId") values ('Southern black-backed gull', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi', 1);
insert into post (title, text, "creatorId") values ('Trumpeter, green-winged', 'purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 1);
insert into post (title, text, "creatorId") values ('Hoary marmot', 'pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam', 1);
insert into post (title, text, "creatorId") values ('Flicker, field', 'tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 1);
insert into post (title, text, "creatorId") values ('Bunting, crested', 'mi in porttitor pede justo eu massa donec dapibus duis at velit', 1);
insert into post (title, text, "creatorId") values ('Chilean flamingo', 'in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis nec euismod', 1);

    `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
