import { MigrationInterface, QueryRunner } from "typeorm";

export class MockPosts1615072596797 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
   insert into post (title, text, "creatorId", "createdAt") values ('Asian false vampire bat', 'ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 1, '2021-03-02T05:45:30Z');
insert into post (title, text, "creatorId", "createdAt") values ('Cormorant, large', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh', 1, '2020-07-18T23:43:49Z');
insert into post (title, text, "creatorId", "createdAt") values ('White-tailed deer', 'dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at', 1, '2020-06-29T20:58:20Z');
insert into post (title, text, "creatorId", "createdAt") values ('Baboon, yellow', 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 1, '2020-03-14T09:22:55Z');
insert into post (title, text, "creatorId", "createdAt") values ('Russian dragonfly', 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam', 1, '2021-01-15T19:10:25Z');
insert into post (title, text, "creatorId", "createdAt") values ('Jackrabbit, white-tailed', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 1, '2021-02-19T19:15:02Z');
insert into post (title, text, "creatorId", "createdAt") values ('Richardson''s ground squirrel', 'mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus', 1, '2020-08-14T06:17:36Z');
insert into post (title, text, "creatorId", "createdAt") values ('Sandhill crane', 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 1, '2021-03-02T19:58:22Z');
insert into post (title, text, "creatorId", "createdAt") values ('Galapagos mockingbird', 'dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis', 1, '2020-11-20T22:13:32Z');
insert into post (title, text, "creatorId", "createdAt") values ('Porcupine, indian', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem', 1, '2020-11-13T02:51:46Z');
insert into post (title, text, "creatorId", "createdAt") values ('Waterbuck, defassa', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra', 1, '2020-07-07T23:47:02Z');
insert into post (title, text, "creatorId", "createdAt") values ('Burchell''s gonolek', 'integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris', 1, '2020-09-04T21:40:08Z');
insert into post (title, text, "creatorId", "createdAt") values ('Goldeneye, common', 'sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 1, '2020-03-10T09:20:01Z');
insert into post (title, text, "creatorId", "createdAt") values ('Galapagos dove', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus', 1, '2020-09-01T18:23:16Z');
insert into post (title, text, "creatorId", "createdAt") values ('Robin, kalahari scrub', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla', 1, '2021-01-05T06:14:16Z');
insert into post (title, text, "creatorId", "createdAt") values ('Two-banded monitor', 'hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo', 1, '2020-08-23T00:24:16Z');
insert into post (title, text, "creatorId", "createdAt") values ('Civet cat', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 1, '2020-10-07T05:46:33Z');
insert into post (title, text, "creatorId", "createdAt") values ('Falcon, prairie', 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla', 1, '2021-03-01T00:36:26Z');
insert into post (title, text, "creatorId", "createdAt") values ('Trumpeter, green-winged', 'nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque', 1, '2020-11-10T18:35:38Z');
insert into post (title, text, "creatorId", "createdAt") values ('Robin, white-throated', 'turpis a pede posuere nonummy integer non velit donec diam', 1, '2020-09-01T16:54:30Z');
insert into post (title, text, "creatorId", "createdAt") values ('Dove, white-winged', 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', 1, '2021-01-26T02:38:37Z');
insert into post (title, text, "creatorId", "createdAt") values ('Black bear', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 1, '2021-01-23T15:55:03Z');
insert into post (title, text, "creatorId", "createdAt") values ('Drongo, fork-tailed', 'morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque', 1, '2020-11-09T00:59:02Z');
insert into post (title, text, "creatorId", "createdAt") values ('Kingfisher, pied', 'etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent', 1, '2020-09-29T21:11:42Z');
insert into post (title, text, "creatorId", "createdAt") values ('Komodo dragon', 'fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 1, '2021-02-01T12:53:46Z');
insert into post (title, text, "creatorId", "createdAt") values ('Genet, common', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia', 1, '2021-01-20T06:30:13Z');
insert into post (title, text, "creatorId", "createdAt") values ('Rhesus macaque', 'tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam', 1, '2020-05-30T18:37:23Z');
insert into post (title, text, "creatorId", "createdAt") values ('Hoopoe, eurasian', 'nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero', 1, '2021-02-17T06:44:37Z');
insert into post (title, text, "creatorId", "createdAt") values ('Waxbill, violet-eared', 'platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem', 1, '2020-11-09T22:14:00Z');
insert into post (title, text, "creatorId", "createdAt") values ('Common melba finch', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi', 1, '2020-11-03T16:25:35Z');
insert into post (title, text, "creatorId", "createdAt") values ('Goose, snow', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 1, '2020-11-20T07:57:43Z');
insert into post (title, text, "creatorId", "createdAt") values ('Lion, mountain', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac', 1, '2020-04-13T13:14:29Z');
insert into post (title, text, "creatorId", "createdAt") values ('Hartebeest, red', 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst', 1, '2020-06-30T14:30:11Z');
insert into post (title, text, "creatorId", "createdAt") values ('Lesser double-collared sunbird', 'curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia', 1, '2020-04-09T02:23:47Z');
insert into post (title, text, "creatorId", "createdAt") values ('Blue catfish', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id', 1, '2020-12-01T13:46:37Z');
insert into post (title, text, "creatorId", "createdAt") values ('King vulture', 'egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla', 1, '2020-10-03T07:21:37Z');
insert into post (title, text, "creatorId", "createdAt") values ('Bengal vulture', 'congue elementum in hac habitasse platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec', 1, '2020-06-05T00:48:59Z');
insert into post (title, text, "creatorId", "createdAt") values ('Jabiru stork', 'nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', 1, '2021-02-05T15:29:32Z');
insert into post (title, text, "creatorId", "createdAt") values ('Northern fur seal', 'condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit', 1, '2021-02-01T23:08:17Z');
insert into post (title, text, "creatorId", "createdAt") values ('Spider, wolf', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis', 1, '2021-01-14T04:35:12Z');
insert into post (title, text, "creatorId", "createdAt") values ('Stork, saddle-billed', 'cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer', 1, '2020-06-14T08:15:01Z');
insert into post (title, text, "creatorId", "createdAt") values ('Bushbuck', 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 1, '2021-02-03T01:27:43Z');
insert into post (title, text, "creatorId", "createdAt") values ('Eastern dwarf mongoose', 'a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 1, '2020-06-05T02:38:24Z');
insert into post (title, text, "creatorId", "createdAt") values ('White-throated robin', 'faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo', 1, '2020-07-16T12:08:56Z');
insert into post (title, text, "creatorId", "createdAt") values ('Owl, australian masked', 'in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi', 1, '2020-10-22T15:35:46Z');
insert into post (title, text, "creatorId", "createdAt") values ('Squirrel glider', 'semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan', 1, '2020-07-21T02:58:04Z');
insert into post (title, text, "creatorId", "createdAt") values ('Cereopsis goose', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac', 1, '2020-06-03T08:39:59Z');
insert into post (title, text, "creatorId", "createdAt") values ('Ovenbird', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 1, '2021-03-03T03:55:48Z');
insert into post (title, text, "creatorId", "createdAt") values ('Hippopotamus', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor', 1, '2020-12-27T22:55:48Z');
insert into post (title, text, "creatorId", "createdAt") values ('Wildebeest, blue', 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis', 1, '2020-05-03T06:34:38Z');
insert into post (title, text, "creatorId", "createdAt") values ('Deer, red', 'non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 1, '2020-07-03T04:35:02Z');
insert into post (title, text, "creatorId", "createdAt") values ('Ring dove', 'condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 1, '2020-03-29T05:39:03Z');
insert into post (title, text, "creatorId", "createdAt") values ('Gila monster', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 1, '2020-05-06T05:40:56Z');
insert into post (title, text, "creatorId", "createdAt") values ('Eastern quoll', 'accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla', 1, '2020-08-06T08:10:31Z');
insert into post (title, text, "creatorId", "createdAt") values ('Owl, australian masked', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla', 1, '2021-01-13T03:44:10Z');
insert into post (title, text, "creatorId", "createdAt") values ('Fox, bat-eared', 'porttitor id consequat in consequat ut nulla sed accumsan felis ut at', 1, '2020-12-09T21:46:03Z');
insert into post (title, text, "creatorId", "createdAt") values ('Raccoon, common', 'volutpat quam pede lobortis ligula sit amet eleifend pede libero quis', 1, '2021-01-08T16:10:44Z');
insert into post (title, text, "creatorId", "createdAt") values ('Skunk, striped', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', 1, '2020-05-28T20:47:07Z');
insert into post (title, text, "creatorId", "createdAt") values ('Lemming, collared', 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin', 1, '2021-02-20T14:56:37Z');
insert into post (title, text, "creatorId", "createdAt") values ('Vulture, oriental white-backed', 'neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', 1, '2021-01-06T22:40:00Z');
insert into post (title, text, "creatorId", "createdAt") values ('Squirrel, richardson''s ground', 'venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet', 1, '2020-04-14T23:55:30Z');
insert into post (title, text, "creatorId", "createdAt") values ('Black-crowned night heron', 'ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin', 1, '2020-12-02T00:01:05Z');
insert into post (title, text, "creatorId", "createdAt") values ('Coqui partridge', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', 1, '2020-10-20T20:36:34Z');
insert into post (title, text, "creatorId", "createdAt") values ('White-bellied sea eagle', 'consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce', 1, '2021-02-24T14:16:02Z');
insert into post (title, text, "creatorId", "createdAt") values ('Common wombat', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 1, '2021-01-23T20:19:52Z');
insert into post (title, text, "creatorId", "createdAt") values ('Great cormorant', 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id', 1, '2021-02-14T17:25:00Z');
insert into post (title, text, "creatorId", "createdAt") values ('American marten', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 1, '2020-06-03T14:18:00Z');
insert into post (title, text, "creatorId", "createdAt") values ('Bonnet macaque', 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate', 1, '2020-11-07T03:08:57Z');
insert into post (title, text, "creatorId", "createdAt") values ('Nine-banded armadillo', 'dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis', 1, '2020-06-18T07:27:49Z');
insert into post (title, text, "creatorId", "createdAt") values ('White-winged dove', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac', 1, '2020-10-31T23:26:43Z');
insert into post (title, text, "creatorId", "createdAt") values ('Agouti', 'leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', 1, '2020-11-15T19:02:00Z');
insert into post (title, text, "creatorId", "createdAt") values ('Common brushtail possum', 'eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 1, '2020-08-31T18:23:22Z');
insert into post (title, text, "creatorId", "createdAt") values ('Turkey, australian brush', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam', 1, '2020-06-03T10:44:33Z');
insert into post (title, text, "creatorId", "createdAt") values ('European shelduck', 'lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien', 1, '2020-12-01T22:09:30Z');
insert into post (title, text, "creatorId", "createdAt") values ('Mynah, indian', 'nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque', 1, '2020-04-05T18:53:11Z');
insert into post (title, text, "creatorId", "createdAt") values ('Openbill stork', 'lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti', 1, '2020-11-21T04:25:46Z');
insert into post (title, text, "creatorId", "createdAt") values ('Yellow-rumped siskin', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis', 1, '2020-11-16T15:33:30Z');
insert into post (title, text, "creatorId", "createdAt") values ('Common waterbuck', 'felis ut at dolor quis odio consequat varius integer ac', 1, '2021-02-13T01:22:11Z');
insert into post (title, text, "creatorId", "createdAt") values ('Goose, andean', 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque', 1, '2020-06-03T08:05:41Z');
insert into post (title, text, "creatorId", "createdAt") values ('Great egret', 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla', 1, '2020-03-20T02:58:10Z');
insert into post (title, text, "creatorId", "createdAt") values ('Penguin, fairy', 'quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 1, '2021-01-02T16:01:15Z');
insert into post (title, text, "creatorId", "createdAt") values ('Mongoose, small indian', 'orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 1, '2020-07-03T23:33:35Z');
insert into post (title, text, "creatorId", "createdAt") values ('Shrike, common boubou', 'platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id', 1, '2020-10-10T08:26:13Z');
insert into post (title, text, "creatorId", "createdAt") values ('African darter', 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at', 1, '2020-08-26T10:23:56Z');
insert into post (title, text, "creatorId", "createdAt") values ('Iguana, common green', 'curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 1, '2020-06-09T11:36:36Z');
insert into post (title, text, "creatorId", "createdAt") values ('Python, carpet', 'consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae', 1, '2020-10-14T00:01:17Z');
insert into post (title, text, "creatorId", "createdAt") values ('Mouflon', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices', 1, '2020-05-18T19:42:46Z');
insert into post (title, text, "creatorId", "createdAt") values ('Goldeneye, barrows', 'sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui', 1, '2020-06-16T04:32:31Z');
insert into post (title, text, "creatorId", "createdAt") values ('Gulls (unidentified)', 'congue risus semper porta volutpat quam pede lobortis ligula sit', 1, '2021-01-02T07:04:11Z');
insert into post (title, text, "creatorId", "createdAt") values ('Bontebok', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id', 1, '2021-02-17T23:49:48Z');
insert into post (title, text, "creatorId", "createdAt") values ('Giant girdled lizard', 'aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum', 1, '2020-04-04T23:33:57Z');
insert into post (title, text, "creatorId", "createdAt") values ('Moccasin, water', 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 1, '2020-09-08T06:10:13Z');
insert into post (title, text, "creatorId", "createdAt") values ('Bettong, brush-tailed', 'rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis', 1, '2020-10-25T04:56:36Z');
insert into post (title, text, "creatorId", "createdAt") values ('Wallaby, agile', 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 1, '2020-10-13T13:43:19Z');
insert into post (title, text, "creatorId", "createdAt") values ('Mongoose, small indian', 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare', 1, '2020-10-31T13:26:05Z');
insert into post (title, text, "creatorId", "createdAt") values ('Possum, pygmy', 'metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus', 1, '2020-04-11T05:30:17Z');
insert into post (title, text, "creatorId", "createdAt") values ('Macaque, rhesus', 'facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 1, '2020-09-11T01:27:12Z');
insert into post (title, text, "creatorId", "createdAt") values ('Jaeger, long-tailed', 'amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate', 1, '2020-09-13T07:59:14Z');
insert into post (title, text, "creatorId", "createdAt") values ('European spoonbill', 'morbi odio odio elementum eu interdum eu tincidunt in leo maecenas', 1, '2020-07-30T22:37:41Z');
insert into post (title, text, "creatorId", "createdAt") values ('King cormorant', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper', 1, '2020-03-22T15:22:23Z');

    `);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
